# @package _global_

defaults:
  - base

robot:
  body_names: [
     # Base
    'Pelvis',
    
    # Left Leg
    'L_hip', 'L_hip2', 'L_thigh', 'L_calf', 'L_toe',
    
    # Right Leg  
    'R_hip', 'R_hip2', 'R_thigh', 'R_calf', 'R_toe',
    
    # Torso
    'Torso',

    # Left Arm
    'L_shoulder_pitch', 'L_shoulder_roll', 'L_shoulder_yaw', 'L_elbow',
    
    # Right Arm
    'R_shoulder_pitch', 'R_shoulder_roll', 'R_shoulder_yaw', 'R_elbow', 
  ]

  dof_names: [
    # Left leg
    'L_hip_joint',
    'L_hip2_joint',
    'L_thigh_joint',
    'L_calf_joint',
    'L_toe_joint',
    # Right leg
    'R_hip_joint',
    'R_hip2_joint',
    'R_thigh_joint',
    'R_calf_joint',
    'R_toe_joint',
    # Upper body
    'Waist_joint',
    # Left arm
    'L_shoulder_pitch_joint',
    'L_shoulder_roll_joint', 
    'L_shoulder_yaw_joint',
    'L_elbow_joint',
    # Right arm
    'R_shoulder_pitch_joint',
    'R_shoulder_roll_joint',
    'R_shoulder_yaw_joint', 
    'R_elbow_joint',  
  ]


  trackable_bodies_subset: [
    "Pelvis",
    "Torso",

    "L_shoulder_roll",
    "R_shoulder_roll",

    "L_elbow",
    "R_elbow",

    "L_thigh",
    "R_thigh",

    "L_calf",
    "R_calf",

    "L_toe",
    "R_toe",
  ]

  # Observation parameters
  dof_obs_size: ${eval:${len:${.dof_body_ids}}*6}
  number_of_actions: 19
  self_obs_max_coords_size: 298  # ${eval:1+20*(3+6+3+3)-3}

  # Control parameters
  dof_body_ids: [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 ]
  joint_axis: ['y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y']
  dof_effort_limits: [200., 200., 200., 300., 40., 200., 200., 200., 300., 40., 200., 40., 40., 18., 18., 40., 40., 18., 18.]
  dof_vel_limits: [23., 23., 23., 14., 9., 23., 23., 23., 14., 9., 23., 9., 9., 20., 20., 9., 9., 20., 20.]
  dof_armatures: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  dof_joint_frictions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  key_bodies: [ "L_toe", "R_toe", "L_elbow",  "R_elbow" ]
  non_termination_contact_bodies: [ "L_toe", "R_toe"]
  right_foot_name: "R_toe"
  left_foot_name: "L_toe"
  head_body_name: "Torso"

  init_state:
    pos: [ 0.0, 0.0, 1.05 ] # x,y,z [m]
    default_joint_angles: # = target angles [rad] when action = 0.0
      # These bias the controller and are recommended to be set at 0.
      L_hip_joint: 0.0
      L_hip2_joint: 0.0
      L_thigh_joint: -0.4
      L_calf_joint: -0.7
      L_toe_joint: 0.3
      # Right leg
      R_hip_joint: 0.0
      R_hip2_joint: 0.0
      R_thigh_joint: -0.4
      R_calf_joint: -0.7
      R_toe_joint: 0.3
      # Upper body
      Waist_joint: 0.0
      # Left arm
      L_shoulder_pitch_joint: 0.0
      L_shoulder_roll_joint: 0.0 
      L_shoulder_yaw_joint: 0.0
      L_elbow_joint: -1.2
      # Right arm
      R_shoulder_pitch_joint: 0.0
      R_shoulder_roll_joint: 0.0
      R_shoulder_yaw_joint: 0.0 
      R_elbow_joint: -1.2  

  control:
    control_type: proportional
    use_biased_controller: False  # See default_joint_angles
    map_actions_to_pd_range: True
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_joint: 200
      hip2_joint: 200
      thigh_joint: 200
      calf_joint: 300
      toe_joint: 40
      Waist_joint: 300
      shoulder_pitch_joint: 100
      shoulder_roll_joint: 100
      shoulder_yaw_joint: 100
      elbow_joint: 100
    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_joint: 5
      hip2_joint: 5
      thigh_joint: 5
      calf_joint: 6
      toe_joint: 2
      Waist_joint: 6
      shoulder_pitch_joint: 2
      shoulder_roll_joint: 2
      shoulder_yaw_joint: 2
      elbow_joint: 2

  asset:
    collapse_fixed_joints: False # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    asset_file_name: "urdf/wholebody_4_dof_arm.urdf"
    usd_asset_file_name: "usd/aidin_humanoid/wholebody_4_dof_arm.usd"
    robot_type: aidin_humanoid
    self_collisions: True
    default_dof_drive_mode: 3

  sim:
    isaacgym:
      fps: 200
      decimation: 4
      substeps: 1
    isaaclab:
      fps: 200
      decimation: 4
    genesis:
      fps: 200
      decimation: 4
      substeps: 1


# Override motion lib default to use the adapted H1 variant
motion_lib:
  _target_: protomotions.utils.motion_lib_aidin_humanoid.AidinHumanoidMotionLib

# Override simulation config to use the adapted H1 variant
env:
  config:
    mimic_reset_track:
      grace_period: 10
