# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 20
  dof_obs_size: 19
  actions_dim: 19
  lower_body_actions_dim: 10 # Yuanhang
  upper_body_actions_dim: 9 # Yuanhang
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1
  # policy_obs_dim: 45 # Jiawei
  # critic_obs_dim: 238
  # policy_obs_dim: 45 # Jiawei
  # policy_obs_dim: 241 # Jiawei
  # self_obs_max_coords: 298  # ${eval:1+20*(3+6+3+3)-3}

  key_bodies: ["R_toe", "L_toe"]
  contact_bodies: [ "R_toe", "L_toe" ]
  num_feet: 2
  right_foot_name: "R_toe"
  left_foot_name: "L_toe"
  foot_name: "_toe"
  knee_name: "_calf"
  has_torso: True
  torso_name: "Torso"
  has_upper_body_dof: True
  # All DOF names for the robot
  dof_names: [
    # Left leg
    'L_hip_joint',
    'L_hip2_joint',
    'L_thigh_joint',
    'L_calf_joint',
    'L_toe_joint',
    # Right leg
    'R_hip_joint',
    'R_hip2_joint',
    'R_thigh_joint',
    'R_calf_joint',
    'R_toe_joint',
    # Upper body
    'Waist_joint',
    # Left arm
    'L_shoulder_pitch_joint',
    'L_shoulder_roll_joint', 
    'L_shoulder_yaw_joint',
    'L_elbow_joint',
    # Right arm
    'R_shoulder_pitch_joint',
    'R_shoulder_roll_joint',
    'R_shoulder_yaw_joint', 
    'R_elbow_joint',
  ]

  # Upper body DOF names
  upper_dof_names: [
    'Waist_joint',
    # Left arm
    'L_shoulder_pitch_joint',
    'L_shoulder_roll_joint',
    'L_shoulder_yaw_joint',
    'L_elbow_joint',
    # Right arm
    'R_shoulder_pitch_joint',
    'R_shoulder_roll_joint',
    'R_shoulder_yaw_joint',
    'R_elbow_joint'
  ]

  # Left arm DOF names
  upper_left_arm_dof_names: [
    'L_shoulder_pitch_joint',
    'L_shoulder_roll_joint',
    'L_shoulder_yaw_joint',
    'L_elbow_joint'
  ]

  # Right arm DOF names
  upper_right_arm_dof_names: [
    'R_shoulder_pitch_joint',
    'R_shoulder_roll_joint',
    'R_shoulder_yaw_joint',
    'R_elbow_joint'
  ]

  # Lower body DOF names
  lower_dof_names: [
    # Left leg
    'L_hip_joint',
    'L_hip2_joint',
    'L_thigh_joint',
    'L_calf_joint',
    'L_toe_joint',
    # Right leg
    'R_hip_joint',
    'R_hip2_joint',
    'R_thigh_joint',
    'R_calf_joint',
    'R_toe_joint'
  ]
  waist_dof_names: ['Waist_joint']
  dof_pos_lower_limit_list: [
    -0.79,    # L_hip_joint
    -0.7,     # L_hip2_joint
    -2.44,    # L_thigh_joint
    -2.09,    # L_calf_joint
    -0.7854,  # L_toe_joint
    -0.61,    # R_hip_joint
    -0.52,    # R_hip2_joint
    -2.44,    # R_thigh_joint
    -2.09,    # R_calf_joint
    -0.7854,  # R_toe_joint
    -0.87,    # Waist_joint
    -3.14,    # L_shoulder_pitch_joint
    -0.087,   # L_shoulder_roll_joint
    -1.57,    # L_shoulder_yaw_joint
    -1.9,     # L_elbow_joint
    -3.14,    # R_shoulder_pitch_joint
    -2.62,    # R_shoulder_roll_joint
    -1.57,    # R_shoulder_yaw_joint
    -1.9      # R_elbow_joint
  ]

  dof_pos_upper_limit_list: [
    0.61,     # L_hip_joint (from URDF: upper="0.61")
    0.52,     # L_hip2_joint (from URDF: upper="0.52")
    0.35,     # L_thigh_joint (from URDF: upper="0.35")
    2.09,     # L_calf_joint (from URDF: upper="2.09")
    0.7854,   # L_toe_joint (from URDF: upper="0.7854")
    0.79,     # R_hip_joint (from URDF: upper="0.79")
    0.7,      # R_hip2_joint (from URDF: upper="0.7")
    0.35,     # R_thigh_joint (from URDF: upper="0.35")
    2.09,     # R_calf_joint (from URDF: upper="2.09")
    0.7854,   # R_toe_joint (from URDF: upper="0.7854")
    0.87,     # Waist_joint (from URDF: upper="0.87")
    1.05,     # L_shoulder_pitch_joint (from URDF: upper="1.05")
    2.62,     # L_shoulder_roll_joint (from URDF: upper="2.62")
    1.57,     # L_shoulder_yaw_joint (from URDF: upper="1.57")
    1.05,     # L_elbow_joint (from URDF: upper="1.05")
    1.05,     # R_shoulder_pitch_joint (from URDF: upper="1.05")
    0.087,    # R_shoulder_roll_joint (from URDF: upper="0.087")
    1.57,     # R_shoulder_yaw_joint (from URDF: upper="1.57")
    1.05      # R_elbow_joint (from URDF: upper="1.05")
  ]

  dof_vel_limit_list: [
    50.0,    # L_hip_joint        (from URDF)
    50.0,    # L_hip2_joint       (from URDF)
    50.0,    # L_thigh_joint      (from URDF)
    50.0,    # L_calf_joint       (from URDF)
    50.0,    # L_toe_joint        (from URDF)
    50.0,    # R_hip_joint        (from URDF)
    50.0,    # R_hip2_joint       (from URDF)
    50.0,    # R_thigh_joint      (from URDF)
    50.0,    # R_calf_joint       (from URDF)
    50.0,    # R_toe_joint        (from URDF)
    13.0,    # Waist_joint        (from URDF)
    16.0,    # L_shoulder_pitch_joint (from URDF)
    16.0,    # L_shoulder_roll_joint  (from URDF)
    8.5,     # L_shoulder_yaw_joint   (from URDF)
    8.5,     # L_elbow_joint          (from URDF)
    16.0,    # R_shoulder_pitch_joint (from URDF)
    16.0,    # R_shoulder_roll_joint  (from URDF)
    8.5,     # R_shoulder_yaw_joint   (from URDF)
    8.5      # R_elbow_joint          (from URDF)
  ]

  dof_effort_limit_list: [
    300.0,   # L_hip_joint        (from URDF)
    300.0,   # L_hip2_joint       (from URDF)
    300.0,   # L_thigh_joint      (from URDF)
    300.0,   # L_calf_joint       (from URDF)
    100.0,   # L_toe_joint        (from URDF)
    300.0,   # R_hip_joint        (from URDF)
    300.0,   # R_hip2_joint       (from URDF)
    300.0,   # R_thigh_joint      (from URDF)
    300.0,   # R_calf_joint       (from URDF)
    100.0,    # R_toe_joint        (from URDF)
    100.0,   # Waist_joint        (from URDF)
    55.0,    # L_shoulder_pitch_joint (from URDF)
    55.0,    # L_shoulder_roll_joint  (from URDF)
    30.0,    # L_shoulder_yaw_joint   (from URDF)
    30.0,    # L_elbow_joint          (from URDF)
    55.0,    # R_shoulder_pitch_joint (from URDF)
    55.0,    # R_shoulder_roll_joint  (from URDF)
    30.0,    # R_shoulder_yaw_joint   (from URDF)
    30.0     # R_elbow_joint          (from URDF)
  ]
  
  # # only apply for isaacsim
  # dof_armature_list: [0.03] * 19  # Using same value for all joints
  # # only apply for isaacsim
  # dof_joint_friction_list: [0.03] * 19  # Using same value for all joints

  body_names: [
    # Base
    'Pelvis',
    
    # Left Leg
    'L_hip', 'L_hip2', 'L_thigh', 'L_calf', 'L_toe',
    
    # Right Leg  
    'R_hip', 'R_hip2', 'R_thigh', 'R_calf', 'R_toe',
    
    # Torso
    'Torso',

    # Left Arm
    'L_shoulder_pitch', 'L_shoulder_roll', 'L_shoulder_yaw', 'L_elbow',
    
    # Right Arm
    'R_shoulder_pitch', 'R_shoulder_roll', 'R_shoulder_yaw', 'R_elbow',
  ]


  terminate_after_contacts_on : ["Torso"]
  penalize_contacts_on: ["Torso"]
  init_state:
    pos: [0.0, 0.0, 0.9] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      L_hip_joint: 0.0
      L_hip2_joint: 0.0
      L_thigh_joint: -0.76
      L_calf_joint: -1.21
      L_toe_joint: 0.14
      R_hip_joint: 0.0
      R_hip2_joint: 0.0
      R_thigh_joint: -0.76
      R_calf_joint: -1.21
      R_toe_joint: 0.14
      Waist_joint: 0.0
      L_shoulder_pitch_joint: 0.37
      L_shoulder_roll_joint: 0.0
      L_shoulder_yaw_joint: 0.0
      L_elbow_joint: -0.94
      R_shoulder_pitch_joint: 0.37
      R_shoulder_roll_joint: 0.0
      R_shoulder_yaw_joint: 0.0
      R_elbow_joint: -0.94


  #! The randomization setting is set to be False for now.
  randomize_link_body_names: [
    'pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link',
    'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link',
  ]

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      L_hip_joint: 100
      L_hip2_joint: 100
      L_thigh_joint: 100
      L_calf_joint: 200
      L_toe_joint: 20
      R_hip_joint: 100
      R_hip2_joint: 100
      R_thigh_joint: 100
      R_calf_joint: 200
      R_toe_joint: 20
      Waist_joint: 100
      L_shoulder_pitch_joint: 90
      L_shoulder_roll_joint: 60
      L_shoulder_yaw_joint: 20
      L_elbow_joint: 60
      R_shoulder_pitch_joint: 90
      R_shoulder_roll_joint: 60
      R_shoulder_yaw_joint: 20
      R_elbow_joint: 60

    damping: # [N*m*s/rad]
      L_hip_joint: 2.5
      L_hip2_joint: 2.5
      L_thigh_joint: 2.5
      L_calf_joint: 5.0
      L_toe_joint: 0.2
      R_hip_joint: 2.5
      R_hip2_joint: 2.5
      R_thigh_joint: 2.5
      R_calf_joint: 5.0
      R_toe_joint: 0.2
      Waist_joint: 2.5
      L_shoulder_pitch_joint: 2.0
      L_shoulder_roll_joint: 1.0
      L_shoulder_yaw_joint: 0.4
      L_elbow_joint: 1.0
      R_shoulder_pitch_joint: 2.0
      R_shoulder_roll_joint: 1.0
      R_shoulder_yaw_joint: 0.4
      R_elbow_joint: 1.0

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "aidin/250527_wholebody_URDF/wholebody_4_dof_arm/wholebody_4_dof_arm.urdf"
    # usd_file: "g1/${robot.asset.robot_type}.usd"
    # xml_file: "g1/${robot.asset.robot_type}.xml"
    # xml_file: "g1/${robot.asset.robot_type}_fitmotionONLY.xml"
    robot_type: aidin_4dof_arm
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

    fix_base_link: False # TEST: fix base link to world

  motion:
    motion_file : 'humanoidverse/data/motions/g1_29dof_anneal_23dof/v1/amass_all.pkl'
    # motion_file : 'humanoidverse/data/motions/g1_29dof/v1/singles/0-ACCAD_Male2General_c3d_A6- Box lift_poses.pkl'
    asset:
      assetRoot: "humanoidverse/data/robots/g1/"
      # assetFileName: "g1_29dof_anneal_23dof.xml"
      assetFileName: "g1_29dof_anneal_23dof_fitmotionONLY.xml"
      urdfFileName: "g1_29dof_anneal_23dof.urdf"

    humanoid_type: g1_29dof_anneal_23dof
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False # For humanoid's geom toe
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names: ['pelvis', 
                 'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
                 'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
                 'waist_yaw_link', 'waist_roll_link', 'torso_link',
                 'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                 'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']
          
    limb_weight_group: 
      - ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link']
      - ['right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link']
      - ['pelvis', 'waist_yaw_link', 'waist_roll_link', 'torso_link']
      - ['left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link']
      - ['right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

    dof_names: ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
                'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
                'waist_yaw_link', 'waist_roll_link', 'torso_link',
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']
    right_foot_name: 'r_foot_roll'
    left_foot_name: 'l_foot_roll'


    # nums_extend_bodies: 1
    # extend_config:
    #   # - joint_name: "left_hand_link"
    #   #   parent_name: "left_elbow_link"
    #   #   parent_name_simulator: "L_elbow"
    #   #   pos: [0.25, 0.0, 0.0]
    #   #   rot: [1.0, 0.0, 0.0, 0.0] # w x y z
    #   # - joint_name: "right_hand_link"
    #   #   parent_name: "right_elbow_link"
    #   #   parent_name_simulator: "R_elbow"
    #   #   pos: [0.25, 0.0, 0.0]
    #   #   rot: [1.0, 0.0, 0.0, 0.0] # w x y z
    #   - joint_name: "head_link"
    #     parent_name: "torso_link"
    #     parent_name_simulator: "Torso"
    #     pos: [0.0, 0.0, 0.42]
    #     rot: [1.0, 0.0, 0.0, 0.0] # w x y z


    motion_tracking_link:
      # - "left_hand_link"
      # - "right_hand_link"
      - "Pelvis"
      - "L_thigh"
      - "L_calf"
      - "R_thigh"
      - "R_calf"
      - "L_elbow"
      - "R_elbow"

    lower_body_link:
      # Base
      - 'Pelvis'
      
      # Left Leg
      - 'L_hip'
      - 'L_hip2'
      - 'L_thigh'
      - 'L_calf'
      - 'L_toe'
      
      # Right Leg  
      - 'R_hip'
      - 'R_hip2'
      - 'R_thigh'
      - 'R_calf'
      - 'R_toe'
      

    upper_body_link:
      # Torso
      - 'Torso'

      # Left Arm
      - 'L_shoulder_pitch'
      - 'L_shoulder_roll'
      - 'L_shoulder_yaw'
      - 'L_elbow'
      
      # Right Arm
      - 'R_shoulder_pitch'
      - 'R_shoulder_roll'
      - 'R_shoulder_yaw'
      - 'R_elbow'
      # - "left_hand_link"
      # - "right_hand_link"
      # - "head_link"
  
      


    pelvis_link: "pelvis"
    base_link: "torso_link"
    hips_link:
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
    
    joint_matches:
      - ["pelvis", "Pelvis"]
      - ["left_hip_pitch_link", "L_Hip"]
      - ["left_knee_link", "L_Knee"]
      - ["left_ankle_roll_link", "L_Ankle"]
      - ["right_hip_pitch_link", "R_Hip"]
      - ["right_knee_link", "R_Knee"]
      - ["right_ankle_roll_link", "R_Ankle"]
      - ["left_shoulder_roll_link", "L_Shoulder"]
      - ["left_elbow_link", "L_Elbow"]
      # - ["left_hand_link", "L_Hand"]
      - ["right_shoulder_roll_link", "R_Shoulder"]
      - ["right_elbow_link", "R_Elbow"]
      # - ["right_hand_link", "R_Hand"]
      # - ["head_link", "Head"]


    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"
      - L_Elbow: "[0, -np.pi/2, 0]"
      - R_Elbow: "[0, np.pi/2, 0]"

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0, 0.351, 0.613] # Pelvis
      - [0.929, 0.867, 0.437] # L_hip
      - [0.929, 0.867, 0.437] # L_hip2
      - [0, 0.351, 0.613] # L_thigh
      - [0, 0.351, 0.613] # L_calf
      - [0, 0.351, 0.613] # L_toe
      - [0.929, 0.867, 0.437] # R_hip
      - [0.929, 0.867, 0.437] # R_hip2
      - [0, 0.351, 0.613] # R_thigh
      - [0, 0.351, 0.613] # R_calf
      - [0, 0.351, 0.613] # R_toe
      - [0.929, 0.867, 0.437]     # Torso
      - [0.929, 0.867, 0.437] # L_shoulder_pitch
      - [0, 0.351, 0.613]     # L_shoulder_roll
      - [0.929, 0.867, 0.437] # L_shoulder_yaw
      - [0, 0.351, 0.613] # L_elbow
      - [0.929, 0.867, 0.437] # R_shoulder_pitch
      - [0, 0.351, 0.613]     # R_shoulder_roll
      - [0.929, 0.867, 0.437] # R_shoulder_yaw
      - [0, 0.351, 0.613] # R_elbow
      # - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
      # - [0.929, 0.867, 0.437] # left_elbow_joint
      # - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
      # - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
      # - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
      # - [0.929, 0.867, 0.437] # right_elbow_joint
      # - [0, 0.351, 0.613] # left_elbow_joint_extend
      # - [0, 0.351, 0.613] # right_elbow_joint_extend
      # - [0, 0.351, 0.613] # head_link

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1

